global using AJE.Ui.News;
global using AJE.Domain;
global using AJE.Infra.Ai;
global using AJE.Infra.Redis;
global using AJE.Infra.FileSystem;
global using AJE.Infra.Translate;
global using StackExchange.Redis;
global using MediatR;
global using System.Text.Json;