global using AJE.Ui.PromptStudio;
global using AJE.Domain;
global using AJE.Infra.Ai;
global using AJE.Infra.Redis;
global using System;
global using StackExchange.Redis;
global using MediatR;
global using System.Text.Json;
global using Microsoft.AspNetCore.SignalR;