// <auto-generated />
using System;
using AJE.Service.NewsAnalyzer.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AJE.Service.NewsAnalyzer.Migrations
{
    [DbContext(typeof(NewsAnalyzerContext))]
    [Migration("20231223172057_LocCorpOrg")]
    partial class LocCorpOrg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AJE.Service.NewsAnalyzer.Infra.AnalysisRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Corporations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corporations");

                    b.Property<int>("CorporationsVersion")
                        .HasColumnType("integer")
                        .HasColumnName("corporationsversion");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locations");

                    b.Property<int>("LocationsVersion")
                        .HasColumnType("integer")
                        .HasColumnName("locationsversion");

                    b.Property<string>("Organizations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organizations");

                    b.Property<int>("OrganizationsVersion")
                        .HasColumnType("integer")
                        .HasColumnName("organizationsversion");

                    b.Property<int>("Polarity")
                        .HasColumnType("integer")
                        .HasColumnName("polarity")
                        .HasAnnotation("Relational:JsonPropertyName", "polarity");

                    b.Property<int>("PolarityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("polarityversion");

                    b.Property<string>("PositiveThings")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("positivethings");

                    b.Property<int>("PositiveThingsVersion")
                        .HasColumnType("integer")
                        .HasColumnName("positivethingsversion");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<int>("SummaryVersion")
                        .HasColumnType("integer")
                        .HasColumnName("summaryversion");

                    b.HasKey("Id");

                    b.ToTable("analysis");
                });
#pragma warning restore 612, 618
        }
    }
}
