// <auto-generated />
using System;
using AJE.Service.NewsAnalyzer.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AJE.Service.NewsAnalyzer.Migrations
{
    [DbContext(typeof(NewsAnalyzerContext))]
    [Migration("20231031184320_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AJE.Service.NewsAnalyzer.Infra.ArticleSentimentPolarityRow", b =>
                {
                    b.Property<int>("Serial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "serial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Serial"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<int>("Polarity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "polarity");

                    b.Property<int>("PolarityVersion")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "polarityVersion");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "source");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                    b.HasKey("Serial");

                    b.ToTable("sentimentpolarities");
                });
#pragma warning restore 612, 618
        }
    }
}
