// <auto-generated />
using AJE.Service.NewsAnalyzer.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AJE.Service.NewsAnalyzer.Migrations
{
    [DbContext(typeof(NewsAnalyzerContext))]
    partial class NewsAnalyzerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AJE.Service.NewsAnalyzer.Infra.ArticleSentimentPolarityRow", b =>
                {
                    b.Property<int>("Serial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("serial")
                        .HasAnnotation("Relational:JsonPropertyName", "serial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Serial"));

                    b.Property<int>("Polarity")
                        .HasColumnType("integer")
                        .HasColumnName("polarity")
                        .HasAnnotation("Relational:JsonPropertyName", "polarity");

                    b.Property<int>("PolarityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("polarityversion")
                        .HasAnnotation("Relational:JsonPropertyName", "polarityVersion");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source")
                        .HasAnnotation("Relational:JsonPropertyName", "source");

                    b.HasKey("Serial");

                    b.ToTable("sentimentpolarities");
                });
#pragma warning restore 612, 618
        }
    }
}
