// <auto-generated />
using System;
using AJE.Service.NewsAnalyzer.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AJE.Service.NewsAnalyzer.Migrations
{
    [DbContext(typeof(NewsAnalyzerContext))]
    partial class NewsAnalyzerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AJE.Service.NewsAnalyzer.Infra.ArticleClassifiedEventRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Polarity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "polarity");

                    b.Property<int>("PolarityVersion")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "polarityVersion");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "source");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "timestamp");

                    b.HasKey("Id");

                    b.ToTable("ArticleClassifiedEventRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
