global using AJE.UnitTests;
global using AJE.Application.Entities;
global using AJE.Application.Queries;
global using AJE.Domain.Entities;
global using Bogus;
global using Moq;
global using StackExchange.Redis;
global using System.Data;
global using Xunit;