global using AJE.Infra;
global using AJE.Application;
global using AJE.Application.Entities;
global using AJE.Domain.Entities;
global using System;
global using System.Text.Json;
global using Microsoft.Extensions.DependencyInjection;
global using StackExchange.Redis;
global using Microsoft.Extensions.Logging;